export const CATAGORIES = [
  "Macro Moments",
  "Wallpapers",
  "Nature",
  "Travel",
  "Architecture & Interiors",
  "Textures & Patterns",
  "Street Photography",
  "Film",
  "Archival",
  "Experimental",
  "Animals",
  "Fashion & Beauty",
  "People",
  "Spirituality",
  "Business & Work",
  "Food & Drink",
  "Health & Wellness",
  "Sports",
  "Current Events",
];
